### ISSUE TITLE
Filter getRenderSettings not working

### ISSUE THREAD

**Issue by billsworld** [sonata-project/SonataDoctrinePhpcrAdminBundle#355]
The line below is returning 'text' rather than 'date' for some reason in Symfony 2.8

https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Filter/DateFilter.php#L81

This forces us to define the date like so.

``` php
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
{
    $datagridMapper
        ->add('createdAt', 'doctrine_phpcr_date', [], 'date')
   ;
}
```

**Comment by dbu** [comment]
not sure if this is a phpcr admin specific issue or a general issue. maybe compare it with the DateFilter of the orm admin - it could be something was refactored and it would be fixed in the orm. then we could do the same here in the phpcr admin.

looking at the code, i think the DateFilter should somehow initialize a default value for its type but it never does.
