### ISSUE TITLE
Document with phpdoc every class

### ISSUE THREAD

**Issue by nacmartin** [sonata-project/SonataDoctrinePhpcrAdminBundle#5]

**Comment by jordisala1991** [comment]
Seems like a lot of time passed since this issue was opened. There are multiple commits and PR that referenced it.

https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/188

On this one @dbu puts this ticket as fixed.

Closing.

If you or @dbu think we should let this open, please ping me or reopen yourself.
